---
- hosts: webservers
  become: yes
    
  tasks:
    - name: Install Apache2  
      apt:
       name: apache2
       state: present
       update_cache: yes
       cache_valid_time: 86400
      tags: apache2

    - name: Install NTP
      apt: 
       name: ntp
       state: present
      tags: ntp

    - name: Start NTP
      service: name=ntp state=started enabled=yes
      tags: ntp_start
